language: go

go:
    - 1.7
install:
- go get -t -v ./...
- go get github.com/golang/lint/golint

script:
    go test -v ./...
    - go vet ./...
    - GOFMT=$(gofmt -d -s .) && echo $GOFMT && test -z "$GOFMT"
