language: go

go:
    - 1.15
install:
    - go get -t -v ./...
    - go get github.com/golang/lint/golint
    - go get golang.org/x/tools/cmd/goimports

script:
    - go test -v ./...
    - GOVET=$(go vet ./...) && echo $GOVET && test -z "$GOVET"
    - GOLINT=$(golint ./...) && echo $GOLINT && test -z "$GOLINT"
    - GOFMT=$(goimports -d .) && echo $GOFMT && test -z "$GOFMT"
